{"name": "To check the functionality of the Home_Page With Valid & Invalid Data.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=94.0.4606.81)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00A5BDE3+2473443]\n\tOrdinal0 [0x009F6661+2057825]\n\tOrdinal0 [0x00902438+1057848]\n\tOrdinal0 [0x008FF031+1044529]\n\tOrdinal0 [0x008F5179+1003897]\n\tOrdinal0 [0x008F5D80+1006976]\n\tOrdinal0 [0x008F53CA+1004490]\n\tOrdinal0 [0x008F4AFA+1002234]\n\tOrdinal0 [0x008F3C8D+998541]\n\tOrdinal0 [0x008F3F46+999238]\n\tOrdinal0 [0x00903A0A+1063434]\n\tOrdinal0 [0x0095506D+1396845]\n\tOrdinal0 [0x009456E3+1332963]\n\tOrdinal0 [0x00954ABF+1395391]\n\tOrdinal0 [0x009455AB+1332651]\n\tOrdinal0 [0x00922104+1188100]\n\tOrdinal0 [0x00922F59+1191769]\n\tGetHandleVerifier [0x00BE2266+1549718]\n\tGetHandleVerifier [0x00C8D4A7+2250711]\n\tGetHandleVerifier [0x00AE718B+521403]\n\tGetHandleVerifier [0x00AE6229+517465]\n\tOrdinal0 [0x009FB79D+2078621]\n\tOrdinal0 [0x009FFB58+2095960]\n\tOrdinal0 [0x009FFC92+2096274]\n\tOrdinal0 [0x00A09541+2135361]\n\tBaseThreadInitThunk [0x75CCFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77607A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77607A4E+238]\n\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\StepDefination.py\", line 13, in step_impl\n    context.driver.get('https://wowdare.xyz')\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User open Browser, Enter Url, Navigate To Log_in Page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=94.0.4606.81)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00A5BDE3+2473443]\n\tOrdinal0 [0x009F6661+2057825]\n\tOrdinal0 [0x00902438+1057848]\n\tOrdinal0 [0x008FF031+1044529]\n\tOrdinal0 [0x008F5179+1003897]\n\tOrdinal0 [0x008F5D80+1006976]\n\tOrdinal0 [0x008F53CA+1004490]\n\tOrdinal0 [0x008F4AFA+1002234]\n\tOrdinal0 [0x008F3C8D+998541]\n\tOrdinal0 [0x008F3F46+999238]\n\tOrdinal0 [0x00903A0A+1063434]\n\tOrdinal0 [0x0095506D+1396845]\n\tOrdinal0 [0x009456E3+1332963]\n\tOrdinal0 [0x00954ABF+1395391]\n\tOrdinal0 [0x009455AB+1332651]\n\tOrdinal0 [0x00922104+1188100]\n\tOrdinal0 [0x00922F59+1191769]\n\tGetHandleVerifier [0x00BE2266+1549718]\n\tGetHandleVerifier [0x00C8D4A7+2250711]\n\tGetHandleVerifier [0x00AE718B+521403]\n\tGetHandleVerifier [0x00AE6229+517465]\n\tOrdinal0 [0x009FB79D+2078621]\n\tOrdinal0 [0x009FFB58+2095960]\n\tOrdinal0 [0x009FFC92+2096274]\n\tOrdinal0 [0x00A09541+2135361]\n\tBaseThreadInitThunk [0x75CCFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77607A7E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77607A4E+238]\n\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\StepDefination.py\", line 13, in step_impl\n    context.driver.get('https://wowdare.xyz')\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1634795007058, "stop": 1634795050912}, {"name": "When User Enter Username With Invalid Data", "status": "skipped", "start": 1634795050914, "stop": 1634795050914}, {"name": "And Click On start Button", "status": "skipped", "start": 1634795050914, "stop": 1634795050914}, {"name": "And User Enter Username With valid Data", "status": "skipped", "start": 1634795050914, "stop": 1634795050914}, {"name": "And User Click on Start Button", "status": "skipped", "start": 1634795050914, "stop": 1634795050914}, {"name": "Then User Should be Navigate to Question Page  Successfully", "status": "skipped", "start": 1634795050914, "stop": 1634795050914}], "start": 1634795006889, "stop": 1634795050914, "uuid": "4c250994-a905-4d71-a479-ad9d7e7407c6", "historyId": "94ced41d7f167e5d1fb1dc9449cf1b30", "fullName": "Wowdare User Side End to End Functionality: To check the functionality of the Home_Page With Valid & Invalid Data.", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "home_page"}, {"name": "feature", "value": "Wowdare User Side End to End Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}